*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Aug 16 02:28:20 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 15 August 2018 18:19:22
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: VM_0_5_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /data/wen
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /data/wen/
your processes number limit is 7283
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.2 (default, Mar 19 2018, 22:59:03)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd13650
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
ModuleNotFoundError: No module named 'blog'
unable to load app 0 (mountpoint='') (callable not found or import error)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd13650 pid: 9958 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9958)
spawned uWSGI worker 1 (pid: 9974, cores: 1)
spawned uWSGI worker 2 (pid: 9975, cores: 1)
spawned uWSGI worker 3 (pid: 9976, cores: 1)
spawned uWSGI worker 4 (pid: 9977, cores: 1)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
Thu Aug 16 02:34:06 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Aug 16 02:34:06 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Aug 16 02:34:06 2018 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Thu Aug 16 02:34:06 2018 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Aug 16 02:39:22 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 15 August 2018 18:19:22
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: VM_0_5_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /data/wen
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /data/wen/
your processes number limit is 7283
your memory page size is 4096 bytes
detected max file descriptor number: 100001
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 3
probably another instance of uWSGI is running on the same address (:8000).
bind(): Address already in use [core/socket.c line 769]
